import org.springframework.boot.gradle.tasks.bundling.BootJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

plugins {
    java
    `java-library`
    kotlin("jvm") version "1.9.22"
    id("org.springframework.boot") version "3.2.3"
}

group = "org.tagioalisi"
version = "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot", "spring-boot-starter-parent", "3.2.3")
    implementation("org.springframework.boot", "spring-boot-starter", "3.2.3")
}

kotlin {
    jvmToolchain(21)
}

tasks.named<BootJar>("bootJar") {
    archiveClassifier.set("boot")
    mainClass.set("org.tagioalisi.TagioalisiMain")
}

//bootJar {
//
//}


