version: '3'
services:
  discordbot:
    image: docker.io/fsufitch/tagioalisi-discordbot
    build:
      context: .
      target: discordbot-runtime
    hostname: discordbot
    env_file:
      - env/defaults/discordbot.env
      - env/discordbot.env

  webapp:
    image: docker.io/fsufitch/tagioalisi-webapp
    build:
      context: .
      target: webapp-runtime
    hostname: webapp
    env_file:
      - env/defaults/webapp.env
      - env/webapp.env

  grpcwebproxy:
    image: docker.io/fsufitch/tagioalisi-grpcwebproxy
    build:
      context: .
      target: grpcwebproxy
    hostname: grpcwebproxy
    env_file:
      - env/defaults/grpcwebproxy.env
      - env/grpcwebproxy.env

  db:
    image: docker.io/fsufitch/tagioalisi-db
    build:
      context: .
      target: database
    env_file:
      - env/defaults/db.env
      - env/db.env
    volumes:
      - type: volume
        source: tagioalisi-db
        target: /var/tagioalisi/db
    networks:
      - tagioalisi

networks:
  tagioalisi:

volumes:
  tagioalisi-db:
