##########
# GRPCWEBPROXY
# This image runs a proxy that converts a pure-gRPC endpoint to a gRPC-web endpoint
# See: https://github.com/improbable-eng/grpc-web/tree/master/go/grpcwebproxy
##########

FROM golang:alpine

RUN go install -v github.com/improbable-eng/grpc-web/go/grpcwebproxy@latest

COPY ./grpcwebproxy /opt/grpcwebproxy

ENV PROXY_BACKEND=localhost:9000
ENV PROXY_BACKEND_TLS=false

ENV PROXY_TLS_PORT=9001
ENV PROXY_TLS_CERT=/opt/grpcwebproxy/default.pem
ENV PROXY_TLS_KEY=/opt/grpcwebproxy/default.key

ENV PROXY_DEBUG_PORT=9002

CMD grpcwebproxy \
        --allow_all_origins \
        --use_websockets \
        --backend_addr ${PROXY_BACKEND} \
        --backend_tls=${PROXY_BACKEND_TLS} \
        --server_http_tls_port ${PROXY_TLS_PORT} \
        --server_tls_cert_file=${PROXY_TLS_CERT} \
        --server_tls_key_file=${PROXY_TLS_KEY}

