version: '3'
services:
  discordbot:
    build: 
      context: .
      dockerfile: Dockerfile.discordbot
      target: devcontainer

    user: "developer"

    networks:
      - tagioalisi

    ports:
      - "8081:8081"
      - "8082:8082"

    volumes:
      - .:/home/developer/tagioalisi-bot:cached
      - $HOME:/home/developer/host-home:cached

    env_file:
      - .env

    environment:
      - DEBUG=true
      - BOT_PORT=8081
      - BOT_GRPC_PORT=8082
      - BLACKLIST_BOT_MODULES=
      - OAUTH_AUTH_ENDPOINT=https://discordapp.com/api/oauth2/authorize
      - OAUTH_TOKEN_ENDPOINT=https://discordapp.com/api/oauth2/token
      - POSTGRES_USER=tagioalisi
      - POSTGRES_PASSWORD=tagi_secret!7461
      - POSTGRES_DB=tagioalisi

  webapp:
    build: 
      context: .
      dockerfile: Dockerfile.webapp
      target: devcontainer


    user: "developer"

    networks:
      - tagioalisi

    ports:
      - "8080:8080"

    volumes:
      - .:/home/developer/tagioalisi-bot:cached
      - $HOME:/home/developer/host-home:cached

    env_file:
      - .env

    environment:
      - BOT_ENDPOINT=http://localhost:8081
      - BOT_GRPC_ENDPOINT=http://localhost:8082

  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      PGDATA: /var/tagioalisi/db/pgdata
    volumes:
      - type: bind
        source: ./var/db
        target: /var/tagioalisi/db

    networks:
      - tagioalisi

    # WARNING: DO NOT EXPOSE PORTS IN PRODUCTION
    ports:
      - "5432:5432"

networks:
  tagioalisi:
