version: '3'
services:
  discordbot:
    build: 
      context: .
      dockerfile: Dockerfile.discordbot
      target: devcontainer

    hostname: dev-discordbot
    user: "developer"

    networks:
      - tagioalisi

    ports:
      - "8081:8081"  # HTTP API
      - "9001:9001"  # gRPC API

    volumes:
      - .:/home/developer/tagioalisi-bot:cached
      - $HOME:/home/developer/host-home:cached

    env_file:
      - .env

    environment:
      - DEBUG=true
      - BOT_PORT=8081
      - BOT_GRPC_PORT=9001
      - BLACKLIST_BOT_MODULES=
      - OAUTH_AUTH_ENDPOINT=https://discordapp.com/api/oauth2/authorize
      - OAUTH_TOKEN_ENDPOINT=https://discordapp.com/api/oauth2/token
      - POSTGRES_USER=tagioalisi
      - POSTGRES_PASSWORD=tagi_secret!7461
      - POSTGRES_DB=tagioalisi

    command:
      sh -c 'while [[ true ]]; do sleep infinity; done'

  webapp:
    build: 
      context: .
      dockerfile: Dockerfile.webapp
      target: devcontainer


    hostname: dev-webapp
    user: "developer"

    networks:
      - tagioalisi

    ports:
      - "8080:8080"

    volumes:
      - .:/home/developer/tagioalisi-bot:cached
      - $HOME:/home/developer/host-home:cached

    env_file:
      - .env

    environment:
      - BOT_ENDPOINT=http://localhost:8081
      - BOT_GRPC_ENDPOINT=https://localhost:8082

    command:
      sh -c 'while [[ true ]]; do sleep infinity; done'
  
  grpcwebproxy:
    build: 
      context: .
      dockerfile: Dockerfile.grpcwebproxy

    hostname: dev-grpcwebproxy
    networks:
      - tagioalisi
    
    environment:
      - PROXY_BACKEND=dev-discordbot:9001

    ports:
      - "8082:9001"

  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      PGDATA: /var/tagioalisi/db/pgdata
    volumes:
      - type: bind
        source: ./var/db
        target: /var/tagioalisi/db

    networks:
      - tagioalisi

    # WARNING: DO NOT EXPOSE PORTS IN PRODUCTION
    ports:
      - "5432:5432"

networks:
  tagioalisi:
