version: '3'

services:
  grpcwebproxy:
    extends:
      file: docker-compose.prod.yml
      service: grpcwebproxy

  db:
    extends:
      file: docker-compose.prod.yml
      service: db
    ports:
      - "5432:5432"

  devcontainer:
    image: docker.io/fsufitch/tagioalisi-devcontainer
    build:
      context: .
      target: devcontainer
    hostname: devcontainer
    networks:
      - tagioalisi
    ports:
      - "8080:8080"  # Webapp
      - "8081:8081"  # HTTP API
      - "9000:9000"  # gRPC API
    env_file:
      - .env
    environment:
      - DEBUG=false
      - BOT_PORT=8081
      - BOT_GRPC_PORT=9000
      - POSTGRES_USER=tagioalisi
      - POSTGRES_PASSWORD=tagi_secret!7461
      - POSTGRES_HOST=db
      - POSTGRES_DB=tagioalisi
    volumes:
      - ./:/home/developer/tagioalisi-bot/
    depends_on:
      - grpcwebproxy
      - db


networks:
  tagioalisi:


volumes:
  tagioalisi-db:
