version: '3'
services:
  discordbot:
    image: docker.io/fsufitch/tagioalisi-discordbot
    build:
      context: .
      target: discordbot-runtime
    hostname: discordbot
    networks:
      - tagioalisi
    ports:
      - "7443:7443"  # HTTPS API
      # gRPC should be exposed via grpcwebproxy
      #- "9000:9000"
    volumes:
      - type: bind
        source: .
        target: /workspaces/tagioalisi-bot
    env_file:
      - env/defaults/discordbot.env
      - env/discordbot.env

  webapp:
    image: docker.io/fsufitch/tagioalisi-webapp
    build:
      context: .
      target: webapp-runtime
    hostname: webapp
    networks:
      - tagioalisi
    ports:
      - "8443:8443" # HTTPS server
    env_file:
      - env/defaults/webapp.env
      - env/webapp.env

  grpcwebproxy:
    image: docker.io/fsufitch/tagioalisi-grpcwebproxy
    build:
      context: .
      target: grpcwebproxy
    hostname: grpcwebproxy
    networks:
      - tagioalisi
    env_file:
      - env/defaults/grpcwebproxy.env
      - env/grpcwebproxy.env
    ports:
      # gRPC requires TLS
      - "9443:9443"

  db:
    image: docker.io/fsufitch/tagioalisi-db
    build:
      context: .
      target: database
    env_file:
      - env/defaults/db.env
      - env/db.env
    volumes:
      - type: volume
        source: tagioalisi-db
        target: /var/tagioalisi/db
    networks:
      - tagioalisi

networks:
  tagioalisi:

volumes:
  tagioalisi-db:
