version: "3"

services:
  devcontainer:
    image: docker.io/fsufitch/tagioalisi-dev
    build:
      context: .
      target: devcontainer
    hostname: devcontainer
    networks:
      - tagioalisi
    ports:
      - 7080:7080
      - 7443:7443
      - 8443:8443
      - 9000:9000
    volumes:
      - .:/workspaces/tagioalisi-bot:z
    env_file:
      - env/defaults/discordbot.env
      - env/defaults/webapp.env
      - env/discordbot.env
      - env/webapp.env

  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - type: volume
        source: tagioalisi-dev-db
        target: /var/tagioalisi/db

  grpcwebproxy:
    extends:
      file: docker-compose.yml
      service: grpcwebproxy
    environment:
      PROXY_BACKEND: devcontainer:9000

networks:
  tagioalisi:

volumes:
  tagioalisi-dev-db: