package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"regexp"
	"strings"
)

var urlRegex = regexp.MustCompile(`\((https?:[^)]*)\)`)

func main() {
	f, err := os.Open("./raw_data.txt")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	data, err := ioutil.ReadAll(f)
	if err != nil {
		panic(err)
	}

	lines := strings.Split(string(data), "\n")
	fmt.Println(`-- Auto-generated by ./memes-seed/build_sql_down.go`)
	fmt.Println(`-- Using memes from https://old.reddit.com/r/image_linker_bot/comments/2znbrg/image_suggestion_thread_20/`)
	for _, line := range lines {
		lineParts := strings.Split(line, "|")

		quotedMemeNames := []string{}
		for _, name := range strings.Split(lineParts[1], ",") {
			quotedMemeNames = append(quotedMemeNames, "'"+strings.ToLower(strings.TrimSpace(name))+"'")
		}

		sql := bytes.NewBufferString("")
		fmt.Fprintf(sql, `
WITH meme_name AS (
	SELECT * FROM meme_names WHERE name IN (%s)
)
DELETE FROM memes WHERE id IN (select meme_id from meme_name);`, strings.Join(quotedMemeNames, ", "))

		fmt.Println(sql.String())
	}
}
