// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: sockpuppet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SockpuppetClient is the client API for Sockpuppet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SockpuppetClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
}

type sockpuppetClient struct {
	cc grpc.ClientConnInterface
}

func NewSockpuppetClient(cc grpc.ClientConnInterface) SockpuppetClient {
	return &sockpuppetClient{cc}
}

func (c *sockpuppetClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, "/tagioalisi.Sockpuppet/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SockpuppetServer is the server API for Sockpuppet service.
// All implementations must embed UnimplementedSockpuppetServer
// for forward compatibility
type SockpuppetServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	mustEmbedUnimplementedSockpuppetServer()
}

// UnimplementedSockpuppetServer must be embedded to have forward compatible implementations.
type UnimplementedSockpuppetServer struct {
}

func (UnimplementedSockpuppetServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedSockpuppetServer) mustEmbedUnimplementedSockpuppetServer() {}

// UnsafeSockpuppetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SockpuppetServer will
// result in compilation errors.
type UnsafeSockpuppetServer interface {
	mustEmbedUnimplementedSockpuppetServer()
}

func RegisterSockpuppetServer(s grpc.ServiceRegistrar, srv SockpuppetServer) {
	s.RegisterService(&Sockpuppet_ServiceDesc, srv)
}

func _Sockpuppet_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SockpuppetServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tagioalisi.Sockpuppet/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SockpuppetServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sockpuppet_ServiceDesc is the grpc.ServiceDesc for Sockpuppet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sockpuppet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tagioalisi.Sockpuppet",
	HandlerType: (*SockpuppetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Sockpuppet_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sockpuppet.proto",
}
