import * as jspb from "google-protobuf";
import * as base_pb from "./base_pb.js";
var goog = jspb;
var global = Function('return this')();
goog.object.extend(proto, base_pb);
goog.exportSymbol('proto.tagioalisi.SendMessageReply', null, global);
goog.exportSymbol('proto.tagioalisi.SendMessageRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tagioalisi.SendMessageRequest = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tagioalisi.SendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.tagioalisi.SendMessageRequest.displayName = 'proto.tagioalisi.SendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tagioalisi.SendMessageReply = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tagioalisi.SendMessageReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    /**
     * @public
     * @override
     */
    proto.tagioalisi.SendMessageReply.displayName = 'proto.tagioalisi.SendMessageReply';
}
if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.tagioalisi.SendMessageRequest.prototype.toObject = function (opt_includeInstance) {
        return proto.tagioalisi.SendMessageRequest.toObject(opt_includeInstance, this);
    };
    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.tagioalisi.SendMessageRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.tagioalisi.SendMessageRequest.toObject = function (includeInstance, msg) {
        var f, obj = {
            jwt: jspb.Message.getFieldWithDefault(msg, 1, ""),
            channelid: jspb.Message.getFieldWithDefault(msg, 2, ""),
            content: jspb.Message.getFieldWithDefault(msg, 3, "")
        };
        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}
/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tagioalisi.SendMessageRequest}
 */
proto.tagioalisi.SendMessageRequest.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.tagioalisi.SendMessageRequest;
    return proto.tagioalisi.SendMessageRequest.deserializeBinaryFromReader(msg, reader);
};
/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tagioalisi.SendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tagioalisi.SendMessageRequest}
 */
proto.tagioalisi.SendMessageRequest.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setJwt(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setChannelid(value);
                break;
            case 3:
                var value = /** @type {string} */ (reader.readString());
                msg.setContent(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};
/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tagioalisi.SendMessageRequest.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.tagioalisi.SendMessageRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};
/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tagioalisi.SendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tagioalisi.SendMessageRequest.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getJwt();
    if (f.length > 0) {
        writer.writeString(1, f);
    }
    f = message.getChannelid();
    if (f.length > 0) {
        writer.writeString(2, f);
    }
    f = message.getContent();
    if (f.length > 0) {
        writer.writeString(3, f);
    }
};
/**
 * optional string jwt = 1;
 * @return {string}
 */
proto.tagioalisi.SendMessageRequest.prototype.getJwt = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};
/**
 * @param {string} value
 * @return {!proto.tagioalisi.SendMessageRequest} returns this
 */
proto.tagioalisi.SendMessageRequest.prototype.setJwt = function (value) {
    return jspb.Message.setProto3StringField(this, 1, value);
};
/**
 * optional string channelID = 2;
 * @return {string}
 */
proto.tagioalisi.SendMessageRequest.prototype.getChannelid = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};
/**
 * @param {string} value
 * @return {!proto.tagioalisi.SendMessageRequest} returns this
 */
proto.tagioalisi.SendMessageRequest.prototype.setChannelid = function (value) {
    return jspb.Message.setProto3StringField(this, 2, value);
};
/**
 * optional string content = 3;
 * @return {string}
 */
proto.tagioalisi.SendMessageRequest.prototype.getContent = function () {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};
/**
 * @param {string} value
 * @return {!proto.tagioalisi.SendMessageRequest} returns this
 */
proto.tagioalisi.SendMessageRequest.prototype.setContent = function (value) {
    return jspb.Message.setProto3StringField(this, 3, value);
};
if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * Optional fields that are not set will be set to undefined.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
     * @param {boolean=} opt_includeInstance Deprecated. whether to include the
     *     JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.tagioalisi.SendMessageReply.prototype.toObject = function (opt_includeInstance) {
        return proto.tagioalisi.SendMessageReply.toObject(opt_includeInstance, this);
    };
    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Deprecated. Whether to include
     *     the JSPB instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.tagioalisi.SendMessageReply} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.tagioalisi.SendMessageReply.toObject = function (includeInstance, msg) {
        var f, obj = {
            status: (f = msg.getStatus()) && base_pb.UnaryStatus.toObject(includeInstance, f)
        };
        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}
/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tagioalisi.SendMessageReply}
 */
proto.tagioalisi.SendMessageReply.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.tagioalisi.SendMessageReply;
    return proto.tagioalisi.SendMessageReply.deserializeBinaryFromReader(msg, reader);
};
/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tagioalisi.SendMessageReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tagioalisi.SendMessageReply}
 */
proto.tagioalisi.SendMessageReply.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = new base_pb.UnaryStatus;
                reader.readMessage(value, base_pb.UnaryStatus.deserializeBinaryFromReader);
                msg.setStatus(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};
/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tagioalisi.SendMessageReply.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.tagioalisi.SendMessageReply.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};
/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tagioalisi.SendMessageReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tagioalisi.SendMessageReply.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getStatus();
    if (f != null) {
        writer.writeMessage(1, f, base_pb.UnaryStatus.serializeBinaryToWriter);
    }
};
/**
 * optional UnaryStatus status = 1;
 * @return {?proto.tagioalisi.UnaryStatus}
 */
proto.tagioalisi.SendMessageReply.prototype.getStatus = function () {
    return /** @type{?proto.tagioalisi.UnaryStatus} */ (jspb.Message.getWrapperField(this, base_pb.UnaryStatus, 1));
};
/**
 * @param {?proto.tagioalisi.UnaryStatus|undefined} value
 * @return {!proto.tagioalisi.SendMessageReply} returns this
*/
proto.tagioalisi.SendMessageReply.prototype.setStatus = function (value) {
    return jspb.Message.setWrapperField(this, 1, value);
};
/**
 * Clears the message field making it undefined.
 * @return {!proto.tagioalisi.SendMessageReply} returns this
 */
proto.tagioalisi.SendMessageReply.prototype.clearStatus = function () {
    return this.setStatus(undefined);
};
/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tagioalisi.SendMessageReply.prototype.hasStatus = function () {
    return jspb.Message.getField(this, 1) != null;
};
// REPLACED BY GOOG_TO_CJS::  goog.object.extend(exports, proto.tagioalisi);
//=== CommonJS exports generated by goog_to_cjs
export const SendMessageReply = proto.tagioalisi.SendMessageReply;
export const SendMessageRequest = proto.tagioalisi.SendMessageRequest;
