-- Auto-generated by ./memes-seed/build_sql_up.go
-- Using memes from https://old.reddit.com/r/image_linker_bot/comments/2znbrg/image_suggestion_thread_20/

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('truestory', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/QanrHU2.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('lennyface', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/g47Stiw.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('aliens', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('aliensguy', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/yEbscSL.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('spidermanneat', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('neat', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/wyhhIYY.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('soon', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/pUNW5cI.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/spQPvYG.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/edE3xEp.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_3 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/aqkP2ib.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_4 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/zEWZR6E.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_5 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/ZLgK9mI.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('tmyk', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('themoreyouknow', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/awczpCj.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsracist', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('datsracist', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dasracist', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/vz0OlTs.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('mybodyisready', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/lMUBzJo.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thisisfine', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gunshowcomic.com/648', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('itsatrap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('admiralackbaritsatrap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ackbar', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('admiralakbar', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ackbaritsatrap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('trap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('admiralackbar', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('atrap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('akbar', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ackbartrap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/LaS80gb.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/P9GLXKX.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsapenisreverse', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('reversethatsapenis', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sinepastaht', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsapenis2', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/AngryZealousAngwantibo', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsmyfetish', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('fetish', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('myfetish', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thisismyfetish', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/OrnateFlawedAfricanclawedfrog', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('idontbelieveyou', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('idontbeleiveyou', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dontbelieveyou', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('anchormanidontbelieveyou', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/SpitefulImmediateGannet', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('costanza', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/G2uNWMn.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgonbgud', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thisgonnabegood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgunbegoodguywithfoldingchair', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgunbegoof', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgunbegood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgonbgood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgunbegud', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgonbegud', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('disgonbegood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thisgunbegood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_10 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thisgonbegood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/ImmenseRectangularCero', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/AmusedImaginativeIbis', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('absolutelydisgusting', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/pt8iaHp.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('deaddove', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('idontknowwhatiexpected', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dontknowwhatiexpected', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/NQookyt.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/GracefulEvilBlackandtancoonhound', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('doubt', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/cIaD7rS.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('slowclap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('claps', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('slowcap', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/6wYnlyj.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('whoosh', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('woosh', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/FirstScentedAstrangiacoral', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('shutupandtakemymoney', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('frytakemymoney', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('takemymoney', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('fryshutupandtakemymoney', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://imgur.com/blqUQAO.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('both', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/dxidUbN.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/DapperDelayedGerbil', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/o2yCYNu.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_3 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/RajOxFU.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('notbad', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('obamanotbad', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/4vXRGQJ.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ohyou', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/DxIhWpb.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('abandonthread', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('fuckthisshitimgoinhome', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('exitthread', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/WateryNeglectedCavy', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('feels', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('myfeels', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/oLyMS8K.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/FT2VXxo.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/LwaOWLk.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('michaelscottno', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('godno', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nogodno', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/SerpentineHeartfeltLarva', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('idontgiveashit', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dontgiveashit', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/HandmadeNegligibleAfricanfisheagle', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sadtennant', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('saddoctor', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('tennantrain', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('saddrwho', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('saddoctorwho', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('doctorwhorain', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('drwhocrying', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('doctorwhocrying', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/LeafyConcernedDassierat', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('redditsilver', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/IA791P4.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('colbertpopcorn', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/MeekPeskyCockroach', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iknowsomeofthesewords', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/UnitedImpureAlaskajingle', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/DQWUdMi.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thanksobama', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/ThoroughIdioticKissingbug', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/qKOhObk.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/L2QPeS1.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_3 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/pIpkcXu.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('foreveralone', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/1O2kNX3.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nathanfillion', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('firefly', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nevermind', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('speechless', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nathanfilionspeechless', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nathanfilion', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nathanfillionspeechless', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('fireflyguy', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/JKsDCgV.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ohgodwhy', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/6RRBfCp.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('lowqualitybait', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/6tSSlgU.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dealwithit', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/LDbhQH4.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/fQFswMx.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/RgLuCO6.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_3 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/yQRuf1z.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_4 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/QXdqtkP.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dickbutt', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/qcF8yPG.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/qnNjJkV.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sadkenau', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/L3RW1CF.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youtried', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('utried', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('tried', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youtriedstar', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/eAhcSTr.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsapenis', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/ExcitableAcrobaticCrane', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('trollface', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/GspFFKf.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('whynotboth', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('porquenodos', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('porquenolasdos', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('porquenolosdos', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/DapperDelayedGerbil', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/o2yCYNu.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('oneartplease', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('artplease', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('zoidbergart', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('zoidbergartplease', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('1artplease', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/ihhjxYs.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('itssomething', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/YtxH6GA.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatescalatedquickly', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/AdolescentUniformKillifish', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/XbF3QKf.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('okay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ok', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/42G7fd8.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('notthebees', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/FpwQnlH.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('feelsbadman', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('feelsbad', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sadface', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/vV4MWrJ.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/T0jNUbo.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youregoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('breakingbadyouregoddamright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('goddamnedright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youregoddamnedright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('goddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yourgoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('heisenberggoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yourgoddamnedright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('breakingbadgoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('breakingbadyouregoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_10 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('heisenbergyouregoddamnright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/jIgWhx6.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/Ck7FO85.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iwanttobelieve', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/SO5eXnK.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('badjokecena', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('johncenastandup', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('cenajokeface', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('cenareaction', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/LjLeJM6.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('goodfellas', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('goodfellows', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/dOBox3c.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ducklaugh', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('duck', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/se6slPr.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('notsureifserious', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('notsureifsrs', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/4y9m2M0.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ihavenoideawhatimdoing', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('chemistrydog', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ihavenoideawhatiamdoing', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('whatamidoing', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ivenoideawhatimdoing', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/yOAbwY3.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/fHRVPXy.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/mY39C4a.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iunderstoodthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('captainamericaiunderstoodthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('capunderstoodreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('reference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iunderstoodthatreferencecaptamerica', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iknowthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('gotthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('inuderstoodthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('igerthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iunderstandthisreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_10 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iunderstoodthisreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_11 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('captainamericareference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_12 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iunderstandthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_13 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('igotthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_14 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iknowthisreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_15 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('igetthatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_16 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('igetthisreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_17 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('captainamerica', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_18 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('referenceunderstood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/jrhY2IW.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ivemadeahugemistake', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('hugemistake', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('imadeahugemistake', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/thJwJbO.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawyeahright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawrenceokay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrenceokthumbsup', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('unimpressedjenniferlawrence', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrenceyeahokay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawok', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrenceokayyeah', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrenceok', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawnodding', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawsarcasticohyeah', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_10 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawokay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_11 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawyeahok', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_12 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawrenceok', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_13 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrencethumbsup', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_14 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawokthumbsup', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_15 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jenniferlawrenceokay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_16 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('jlawohyeahsure', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/xxNaKRy.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('butwhy', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/gtLY9Qv.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/DbHb20Q.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('michaeljacksonpopcorn', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('michaeljackson', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('popcornmj', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('mjpopcorn', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('mjpcorn', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/ElasticRadiantAmericanindianhorse', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('rollsafe', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/Kxsm9vp.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youdarealmvp', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youtherealmvp', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('realmvp', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('therealmvp', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('darealmvp', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/dRHBecg.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nope', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('no', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/MellowConsciousAsianwaterbuffalo', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('2spooky4me', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('2spookyforme', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('toospooky', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('2spooky', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('toospookyforme', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('toospooky4me', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/rXE8P9O.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ifyouknowwhatimean', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/y0OuuYc.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('dozensofus', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('therearedozensofus', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('tobiasdozens', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/MNWxr0Q.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('itshappening', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ronpaul', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ronpaulitshappening', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('happening', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/Hf1yqgr.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('coolstorybro', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('coolstory', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://imgur.com/egich3M.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('facepalm', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/FwsRdVg.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/rOhUhfS.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('slowpoke', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/UlsmWsD.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('mindblown', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('brainexploding', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('headexploding', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/rzKwVq8.gif', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('whatyearisit', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('whatyearisthis', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/omBCzFn.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsthejoke', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatwasthejoke', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thatsthepoint', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('thejoke', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/tEjeMu8.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/GlassAmusingBeardedcollie', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sensiblechuckle', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/K8BQ3w7.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/UCuu9kw.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yeahrightsure', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yarightsure', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yearightsure', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yeahsure', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yeahright', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/gQ0UjTV.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/xxNaKRy.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sickreferencebro', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('greatreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sickrefrence', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('goodreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('referencesoutofcontrol', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sweetreferencebro', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_6 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sickreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_7 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sweetreference', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_8 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('sickrefrencebro', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_9 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yourreferencesareoutofcontrol', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_10 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('broyourreferencesareoutofcontrol', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/AdeptSatisfiedDegu', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('youdontsay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('udontsay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('yadontsay', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/uJtBTE6.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('ayylmao', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/6U8L0pU.gifv', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/FzoVjxc.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('heavybreathing', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/P9TAu3k.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('areyouawizard', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/C8d6rkP.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('rekt', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/7R7SRof.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('feelsgoodman', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('feelsgood', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/GZf4Mv3.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/VXLY2Z3.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/8WIA8Gj.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_3 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('https://i.imgur.com/bbCQBE3.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iseewhatyoudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('seewhatyoudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_2 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iseewhatudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_3 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iseewatudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_4 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('iseewatyoudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_5 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('seewhatudidthere', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/dpG2Swr.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nowkiss', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_names_insert_1 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('nowkith', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/kmjXwTF.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('picardfacepalm', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/FwsRdVg.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('popcorn', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/ElasticRadiantAmericanindianhorse', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_1 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/PaleScentedImpala', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_2 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://gfycat.com/MeekPeskyCockroach', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('motherofgod', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/6iJslps.png', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;

WITH meme AS (
	INSERT INTO memes DEFAULT VALUES RETURNING *
), meme_names_insert_0 as (
	INSERT INTO meme_names(name, timestamp, author, meme_id)
	VALUES('conspiracykeanu', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
), meme_urls_insert_0 as (
	INSERT INTO meme_urls(url, timestamp, author, meme_id)
	VALUES('http://i.imgur.com/3DX9lR5.jpg', '2020-03-06T16:08:45-05:00', 'seed', (SELECT id FROM meme))
	ON CONFLICT DO NOTHING
)
SELECT 1;
