# General
printWidth: 100
endOfLine: lf
embeddedLanguageFormatting: auto

# JS/TS
arrowParens: always
semi: true
singleQuote: true
quoteProps: consistent
trailingComma: all
bracketSpacing: true

# JSX
jsxSingleQuote: false
htmlWhitespaceSensitivity: strict
bracketSameLine: false
singleAttributePerLine: false

# Indentation
useTabs: false
tabWidth: 2

# Markdown
proseWrap: preserve
