version: '3'
services:
  discordbot:
    extends:
      file: docker-compose.base.yml
      service: discordbot
    networks:
      - tagioalisi
    ports:
      - "7443:7443"  # HTTPS API
      # gRPC should be exposed via grpcwebproxy
      #- "9000:9000"

  webapp:
    extends:
      file: docker-compose.base.yml
      service: webapp
    networks:
      - tagioalisi
    ports:
      - "8443:8443" # HTTPS server

  grpcwebproxy:
    extends:
      file: docker-compose.base.yml
      service: grpcwebproxy
    networks:
      - tagioalisi
    ports:
      # gRPC requires TLS
      - "9443:9443"

  db:
    extends:
      file: docker-compose.base.yml
      service: db
    volumes:
      - type: volume
        source: tagioalisi-db
        target: /var/tagioalisi/db
    networks:
      - tagioalisi

networks:
  tagioalisi:

volumes:
  tagioalisi-db:
