FROM nginx:alpine AS ui-server

WORKDIR /tagioalisi-web

COPY binpkg/web.tar.gz .

RUN mkdir -p www && \
    tar xvvfz web.tar.gz -C www && \
    rm web.tar.gz && \
    rm /etc/nginx/conf.d/default.conf

COPY tagioalisi.nginx_template.conf web-entrypoint.sh ./

ENV BOT_EXTERNAL_BASE_URL http://tagioalisi-bot-base-not-set
ENV NGINX_PORT 80

CMD [ "sh", "./web-entrypoint.sh" ]
