root: true
ignorePatterns:
  - '!.*' # Include dot-files so it formats itself and prettier's config

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'

env:
  node: true

rules:
  'import/default': off

parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: 'module'

plugins:
  - '@typescript-eslint'
  - 'import'

settings:
  react:
    version: detect
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
        - webapp/tsconfig.json # This is because VSCode's workspace might be at repo the root, not in this dir
