
# Reference: https://pet2cattle.com/2021/09/build-multiarch-container-github-action
name: Build and Push Tag Image

# Run when a tag is pushed
on:
  push:
    tags:
      - '.*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get Latest Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ranking:${{ steps.vars.outputs.tag }}